INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Colin','Wheeler','Venezuela',97,'Físico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kaitlin','Dickerson','Japan',46,'Capitán');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Sydney','Witt','Kenya',6,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Gisela','York','Ireland',18,'Capitán');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kaye','Walker','Côte DIvoire (Ivory Coast)',9,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kessie','Buchanan','South Georgia and The South Sandwich Islands',56,'Abogado');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Dane','Pugh','Liberia',14,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Madonna','Pope','Kyrgyzstan',44,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Dolan','Mathews','Saint Helena, Ascension and Tristan da Cunha',55,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Emily','Collier','Uzbekistan',24,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Brittany','Lawson','Bonaire, Sint Eustatius and Saba',72,'Capitán');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Ina','Garrett','New Zealand',43,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Francesca','Weiss','Cyprus',94,'Enfermero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Nell','Daniels','Aruba',74,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Petra','Wooten','Bangladesh',15,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Christen','Hutchinson','Macedonia, the former Yugoslav Republic of',18,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Ulysses','Pruitt','British Indian Ocean Territory',18,'Subastero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Sebastian','Lott','Isle of Man',24,'Enfermero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Griffith','Bullock','Vanuatu',1,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Macey','Mcdowell','Singapore',27,'Médico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Tanek','Alvarez','Ethiopia',34,'Enfermero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Marvin','Munoz','Iceland',26,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Caldwell','Lewis','Burundi',25,'Médico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Dennis','Houston','Hong Kong',40,'Vividor');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kelsey','Whitaker','Montserrat',76,'Enfermero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kane','Rowland','Guyana',96,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Amela','Merrill','Saint Martin',27,'Físico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Mannix','Booker','Timor-Leste',53,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Desirae','Lynn','Albania',25,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Jarrod','Hardy','Lithuania',65,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Nora','Lambert','British Indian Ocean Territory',92,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kelly','Dotson','Belize',68,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Ross','Hudson','Switzerland',39,'Abogado');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kessie','Brown','Tuvalu',31,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kadeem','Shepherd','Chad',32,'Enfermero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Willa','Obrien','Saudi Arabia',63,'Abogado');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Jessica','Parks','Saint Lucia',36,'Enfermero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Farrah','Marks','Senegal',38,'Físico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Quentin','Nguyen','Uruguay',43,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Holmes','Dickson','Trinidad and Tobago',94,'CEO');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Garrison','Byrd','Antigua and Barbuda',95,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Nolan','Daugherty','Latvia',75,'Subastero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Gretchen','Baird','Saint Vincent and The Grenadines',70,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Vanna','Padilla','Angola',86,'Enfermero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Timon','Morris','Switzerland',46,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Amy','Sparks','Honduras',27,'Vividor');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Adele','Morton','Aruba',25,'Médico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Galena','Hurst','Malaysia',36,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Clark','Logan','Poland',66,'Capitán');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Nevada','Haley','Northern Mariana Islands',84,'Físico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Timothy','Eaton','Bahamas',31,'Piloto');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Clinton','Parsons','Åland Islands',7,'Médico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Aspen','Daugherty','Hong Kong',96,'Abogado');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Porter','Finley','Saint Pierre and Miquelon',92,'CEO');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Allistair','Nixon','Spain',90,'Vividor');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Audra','Haynes','Saint Lucia',61,'Subastero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Ralph','Everett','Spain',99,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Oren','Wilkins','Tunisia',63,'CEO');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Wang','Frazier','French Polynesia',6,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Indigo','Graham','Gambia',58,'CEO');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Damon','Stanton','Côte DIvoire (Ivory Coast)',26,'Enfermero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Chadwick','Roberson','Senegal',43,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Bell','Mckay','Suriname',88,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Quyn','Larsen','Croatia',92,'Subastero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Dawn','Dillard','Saint Martin',17,'CEO');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Raya','Mays','Bahrain',54,'Subastero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Eagan','Marks','Antarctica',39,'Vividor');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Justin','Lancaster','Somalia',11,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Harlan','Vazquez','Jersey',14,'Piloto');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Debra','Rodriguez','Cyprus',43,'Piloto');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Lucian','Bright','Belgium',76,'Capitán');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Hilel','Gibson','Cyprus',56,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Herrod','Carpenter','Burkina Faso',49,'Subastero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Zenaida','Phelps','Panama',1,'Piloto');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Brielle','Lawrence','Myanmar',79,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Harriet','Wade','Sint Maarten',24,'Abogado');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Simone','Hoffman','Russian Federation',67,'Capitán');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Cooper','Brady','Martinique',63,'Piloto');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Colette','Koch','Barbados',33,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Karly','Levine','Mali',3,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Alexis','Lowery','Lithuania',81,'CEO');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Ahmed','Young','Saint Pierre and Miquelon',51,'Médico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Erin','Allison','France',60,'Físico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Alden','Silva','Cocos (Keeling) Islands',42,'Capitán');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Hamilton','Smith','Latvia',76,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Martena','Foster','Puerto Rico',51,'Developer');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Sage','Solomon','Mexico',5,'Médico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Tatum','Nixon','Svalbard and Jan Mayen Islands',50,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Elvis','Cox','Tanzania',3,'Albañil');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Emi','Owens','Germany',72,'Deportista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Xanthus','Henderson','Sri Lanka',32,'Vividor');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Piper','Snow','Tunisia',23,'Piloto');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Ria','Avila','Benin',79,'Piloto');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Harriet','Alford','Saint Martin',87,'Vividor');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Hayden','Kane','Sao Tome and Principe',66,'CEO');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Kirk','Webb','Uganda',57,'Capitán');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Josiah','Harding','Senegal',98,'Subastero');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Jenna','Haynes','Bouvet Island',70,'Periodista');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Ori','Haynes','Costa Rica',3,'Médico');
INSERT INTO Personas (Nombre,Apellido,Nacionalidad,Edad,Profesion) VALUES ('Conan','Cote','Saint Martin',25,'Subastero');
